on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile program
        run: |
          gcc -o lorenz lorenz.c

      - name: Run tests
        run: |
          ./lorenz
